version: "3.9"

networks:
  app-tier:
    driver: bridge

volumes:
    postgres_data:

name: "lab2"
      
services:
  postgres:
    container_name: lab2
    image: postgres:14.5
    hostname: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    networks:
      - app-tier